# Generated by Django 5.2.8 on 2026-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_key',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
